const {chromium}=require(process.env.PLAYWRIGHT_CORE || 'playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 try{
  const context=await browser.newContext({viewport:{width:1500,height:1000}});
  await context.route(/fonts.googleapis.com|fonts.gstatic.com/,r=>r.abort());
  await context.route('**/local.php?*',r=>r.fulfill({status:503,body:'{"error":"Test drafts"}'}));
  await context.route('**/projects/index.json',r=>r.fulfill({contentType:'application/json',body:'[]'}));
  const page=await context.newPage(), errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.BUILDER_URL || 'http://127.0.0.1:8765/');
  await page.waitForFunction(()=>typeof db!=='undefined' && db);
  await page.locator('#new-client').click();
  await page.locator('input[name=clientName]').fill('Workflow Alpha');
  await page.getByRole('button',{name:'Create client',exact:true}).click();
  await page.locator('.background-presets').waitFor();
  const alpha=await page.evaluate(()=>cur.id);
  await page.locator('[data-path="client.idea"]').fill('Original idea');
  await page.locator('[data-path="client.fullName"]').fill('Edited name');
  await page.locator('#undo-edit').click();
  assert.equal(await page.locator('[data-path="client.fullName"]').inputValue(),'Workflow Alpha');
  await page.locator('#redo-edit').click();
  assert.equal(await page.locator('[data-path="client.fullName"]').inputValue(),'Edited name');
  await page.locator('#undo-edit').click();
  await page.locator('.background-presets [data-v="midnight"]').click();
  assert(await page.locator('#redo-edit').isDisabled(),'A new edit clears redo');
  await page.waitForFunction(()=>document.getElementById('workflow-state').textContent.includes('Draft saved'));
  assert((await page.locator('#workflow-state').textContent()).includes('Unpublished changes'));
  // Keyboard undo outside fields, while native input undo remains untouched.
  await page.locator('#undo-edit').focus();await page.keyboard.press('Control+z');
  assert.equal(await page.evaluate(()=>cur.config.hero.bg),'brand');
  await page.keyboard.press('Control+Shift+z');
  assert.equal(await page.evaluate(()=>cur.config.hero.bg),'midnight');
  await page.locator('#search-settings').click();
  await page.locator('#settings-query').fill('background');
  await page.locator('#settings-results button').first().click();
  assert(await page.locator('.background-presets').isVisible());
  await page.locator('#edit-headings').check();
  await page.waitForFunction(()=>frontFrame.contentDocument?.querySelector('#brand h2')?.tabIndex===0);
  await page.locator('#client-view').click();
  await page.waitForFunction(()=>clientView && !frontFrame.contentDocument?.querySelector('.admin-card-tools') && frontFrame.contentDocument?.querySelector('#brand h2')?.tabIndex===-1);
  assert(await page.locator('#panel').isHidden());
  await page.locator('.pbar [data-w="mobile"]').click();
  assert.equal(await page.locator('#stage').getAttribute('data-w'),'mobile');
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!clientView && frontFrame.contentDocument?.querySelector('.admin-card-tools'));
  assert(await page.locator('#edit-headings').isChecked());
  await page.locator('.pbar [data-w="desktop"]').click();
  const fileChooser=page.waitForEvent('filechooser');
  await page.getByRole('button',{name:'Upload background image',exact:true}).click();
  await (await fileChooser).setFiles({name:'hero.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
  await page.waitForFunction(()=>cur.config.hero.image && !uploading.size);
  for(const [field,value] of [['focalX','25'],['focalY','70'],['zoom','150']]) {
    await page.locator('[data-path="hero.'+field+'"]').fill(value);
  }
  await page.waitForFunction(()=>frontFrame.contentDocument.querySelector('.hero-main')?.style.getPropertyValue('--hero-zoom')==='1.5');
  assert.equal(await page.evaluate(()=>getComputedStyle(frontFrame.contentDocument.querySelector('.hero-main'),'::before').transform),'matrix(1.5, 0, 0, 1.5, 0, 0)');
  await page.locator('#version-history').click();
  await page.locator('#version-form input').fill('Approved design');
  await page.locator('#version-form button').click();
  await page.locator('#version-list .workflow-row').filter({hasText:'Approved design'}).waitFor();
  await page.locator('dialog .workflow-close').click();
  await page.locator('[data-path="client.idea"]').fill('Changed after checkpoint');
  await page.waitForFunction(()=>!dirty);
  await page.reload();
  await page.waitForFunction(()=>typeof cur!=='undefined' && cur?.config.client.idea==='Changed after checkpoint');
  await page.locator('#version-history').click();
  await page.locator('#version-list .workflow-row').filter({hasText:'Approved design'}).getByRole('button',{name:'Restore',exact:true}).click();
  await page.waitForFunction(()=>cur.config.client.idea==='Original idea' && !workflowBusy);
  assert.equal(await page.evaluate(()=>cur.config.hero.zoom),150);
  assert.equal(await page.evaluate(()=>cur.id),alpha,'Restoring retains the permanent client id');
  await page.locator('#undo-edit').click();
  assert.equal(await page.evaluate(()=>cur.config.client.idea),'Changed after checkpoint');
  await page.locator('#redo-edit').click();
  assert.equal(await page.evaluate(()=>cur.config.client.idea),'Original idea');
  await page.waitForFunction(()=>!dirty);
  await page.locator('#brand-templates').click();
  await page.locator('#template-form input').fill('Reusable healthcare');
  await page.locator('#template-form button').click();
  await page.locator('#template-list .workflow-row').filter({hasText:'Reusable healthcare'}).waitFor();
  await page.locator('dialog .workflow-close').click();
  await page.reload();
  await page.waitForFunction(()=>typeof cur!=='undefined' && cur);
  await page.locator('#brand-templates').click();
  await page.locator('#template-list .workflow-row').filter({hasText:'Reusable healthcare'}).getByRole('button',{name:'New client',exact:true}).click();
  await page.locator('input[name=clientName]').fill('Workflow Beta');
  await page.getByRole('button',{name:'Create client',exact:true}).click();
  await page.waitForFunction(()=>cur?.config.client.name==='Workflow Beta');
  assert.notEqual(await page.evaluate(()=>cur.id),alpha);
  assert.equal(await page.evaluate(()=>cur.config.hero.zoom),150);
  assert(await page.evaluate(()=>!!cur.config.hero.image));
  assert(await page.locator('#undo-edit').isDisabled(),'New clients cannot undo into another client');
  await page.locator('#publish-checklist').click();
  assert((await page.locator('dialog').textContent()).includes('No logo files yet'));
  assert((await page.locator('dialog').textContent()).includes('placeholder'));
  assert((await page.locator('dialog').textContent()).includes('link'));
  await page.locator('dialog .workflow-close').click();
  const imagePage=await context.newPage();
  await imagePage.setContent(await page.evaluate(async()=>projectHtml(await packedProject(cur.id,cur.config))));
  assert.equal(await imagePage.locator('.hero-main').evaluate(n=>n.style.getPropertyValue('--hero-zoom')),'1.5');
  assert.equal(await imagePage.locator('.hero-main').evaluate(n=>n.style.getPropertyValue('--hero-x')),'25%');
  await imagePage.close();
  // Check a low-contrast override, independent of the image review note.
  await page.locator('.background-presets [data-v="midnight"]').click();
  await page.locator('[data-path="hero.text"]').selectOption('dark');
  await page.locator('#publish-checklist').click();
  assert((await page.locator('dialog').textContent()).includes('Hero text may be hard to read'));
  await page.locator('dialog .workflow-close').click();
  const exported=await page.evaluate(async()=>projectHtml(await packedProject(cur.id,cur.config)));
  assert(!exported.includes('workflow.js'));
  const client=await context.newPage();await client.setContent(exported);
  assert.equal(await client.locator('#undo-edit,#client-view,.admin-card-tools').count(),0);
  await page.locator('#client-select').selectOption(alpha);
  await page.waitForFunction(id=>cur.id===id,alpha);
  assert.equal(await page.evaluate(()=>cur.config.hero.bg),'image');
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Editor fits on a phone');
  await page.locator('#version-history').click();
  assert(await page.locator('dialog').evaluate(el=>el.getBoundingClientRect().right<=innerWidth),'Dialog fits on a phone');
  await page.locator('dialog .workflow-close').click();
  fs.mkdirSync(__dirname+'/artifacts',{recursive:true});
  await page.screenshot({path:__dirname+'/artifacts/workflow-mobile.png',fullPage:false});
  await page.setViewportSize({width:1500,height:1000});
  await page.screenshot({path:__dirname+'/artifacts/workflow-desktop.png',fullPage:false});
  assert.deepEqual(errors,[]);
  console.log('PASS: undo/redo and keyboard, status, search, client view, crop, persistent checkpoints and templates, restore undo, client isolation, checklist, exported output, mobile layout.');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
